---
# If you wish to update the default configuration values, copy this file and place it under your home dir, under the same name.
# These variables are used to drive the installation of the environment script.
# The variables that start with BESMAN_ are converted to environment vars.
# If you wish to add any other vars that should be used globally, add the var using the below format.
# BESMAN_<var name>: <value>
# If you are not using any particular value, remove it or comment it(#).
#*** - These variables should not be removed, nor left empty.

# Project/ml model/training dataset
BESMAN_ARTIFACT_TYPE: project

# Name of artifact under assessment.
BESMAN_ARTIFACT_NAME: moodle

# Version of artifact under assessment.
BESMAN_ARTIFACT_VERSION: "3.11"

# Source code url of artifact under assessment.
BESMAN_ARTIFACT_URL: https://github.com/moodle/moodle

# Name of environment.
BESMAN_ENV_NAME: moodle-RT-env

# Path to clone source code of artifact under assessment.
BESMAN_ARTIFACT_DIR: $HOME/$BESMAN_ARTIFACT_NAME

# Path to download assessment and other required tools during installation.
BESMAN_TOOL_PATH: /opt #***

# Organization/lab/individual.
BESMAN_LAB_TYPE: Organization #***

# Name of owner of lab. Default is Be-Secure.
BESMAN_LAB_NAME: Be-Secure #***

# Local dir to store assessment reports. Default is home.
BESMAN_ASSESSMENT_DATASTORE_DIR: $HOME/besecure-assessment-datastore #***

# Remote repo to store assessment reports.
BESMAN_ASSESSMENT_DATASTORE_URL: https://github.com/Be-Secure/besecure-assessment-datastore #***

# Add a comma separated list of tools that needs to be installed to assess this project.
BESMAN_ASSESSMENT_TOOLS: spdx-sbom-generator,sonarqube,criticality_score,snyk,fossology