---
# If you wish to update the default configuration values, copy this file and place it under your home dir, under the same name.
# These variables are used to drive the installation of the environment script.
# The variables that start with BESMAN_ are converted to environment vars.
# If you wish to add any other vars that should be used globally, add the var using the below format.
# BESMAN_<var name>: <value>
# If you are not using any particular value, remove it or comment it(#).
#*** - These variables should not be removed, nor left empty.
# used to mention where you should clone the repo from, default value is Be-Secure
BESMAN_ORG: Be-Secure #***

# project/ml model/training dataset
BESMAN_ARTIFACT_TYPE: project

# Name of the artifact under assessment.
BESMAN_ARTIFACT_NAME: modelbench #***

# Version of the artifact under assessment.
BESMAN_ARTIFACT_VERSION: v1.0.0

# Source code url of the artifact under assessment.
BESMAN_ARTIFACT_URL: https://github.com/Be-Secure/modelbench

# Using this variable for scorecard and criticality_score
BESMAN_ARTIFACT_ORIGIN_URL: https://github.com/Be-Secure/modelbench

# This variable stores the name of the environment file.
BESMAN_ENV_NAME: modelbench-RT-env #***

# The path where you wish to clone the source code of the artifact under assessment.
# If you wish to change the clone path, provide the complete path.
BESMAN_ARTIFACT_DIR: $HOME/$BESMAN_ARTIFACT_NAME #***

# The path where we download the assessment and other required tools during installation.
BESMAN_TOOL_PATH: /opt #***

# Organization/lab/individual.
BESMAN_LAB_TYPE: Lab #***

# Name of the owner of the lab. Default is Be-Secure.
BESMAN_LAB_NAME: BeSLab #***

# This is the local dir where we store the assessment reports. Default is home.
BESMAN_ASSESSMENT_DATASTORE_DIR: $HOME/besecure-assessment-datastore #***

# The remote repo where we store the assessment reports.
BESMAN_ASSESSMENT_DATASTORE_URL: https://github.com/Be-Secure/besecure-assessment-datastore #***

# Comma-separated list of tools to manage (e.g., scorecard,criticality_score,sonarqube,fossology,spdx-sbom-generator)
BESMAN_ASSESSMENT_TOOLS: "scorecard,criticality_score,sonarqube,fossology,spdx-sbom-generator"

# Ports for containerized tools
BESMAN_SONARQUBE_PORT: 9000
BESMAN_FOSSOLOGY_PORT: 8080

# SPDX SBOM Generator release asset URL (GitHub or other source)
BESMAN_SPDX_SBOM_ASSET_URL: "https://github.com/spdx/spdx-sbom-generator/releases/latest/download/spdx-sbom-generator-linux-amd64.tar.gz"

# Mode for scorecard cli or github action.
BESMAN_SCORECARD_ASSESSMENT_MODE: "cli"