---
# If you wish to update the default configuration values, copy this file and place it under your home dir, under the same name.
# These variables are used to drive the installation of the environment script.
# The variables that start with BESMAN_ are converted to environment vars.
# If you wish to add any other vars that should be used globally, add the var using the below format.
# BESMAN_<var name>: <value>
# If you are not using any particular value, remove it or comment it(#).
#*** - These variables should not be removed, nor left empty.
# used to mention where you should clone the repo from, default value is Be-Secure
BESMAN_ORG: Be-Secure #***

# project/ml model/training dataset
BESMAN_ARTIFACT_TYPE: ml #***

# Name of the artifact under assessment.
BESMAN_ARTIFACT_NAME: ml-name #***

# Version of the artifact under assessment.
BESMAN_ARTIFACT_VERSION: N/A #***

# Source code url of the artifact under assessment.
BESMAN_ARTIFACT_URL: ml-source-url #***

# This variable stores the name of the environment file.
BESMAN_ENV_NAME: MLAssessment-RT-env #***

# The path where you wish to clone the source code of the artifact under assessment.
# If you wish to change the clone path, provide the complete path.
BESMAN_ARTIFACT_DIR: $HOME/ml-assessment-env #***

BESMAN_ENV_DIR: $HOME/ml-assessment-env
BESMAN_VENV_NAME: ml-assessment-venv
BESMAN_ART_REPO: https://github.com/NeerajK007/adversarial-robustness-toolbox.git
BESMAN_WT_REPO: https://github.com/NeerajK007/watchtower.git
BESMAN_TOOLS_DIR: $BESMAN_ENV_DIR/tools

# The path where we download the assessment and other required tools during installation.
BESMAN_TOOL_PATH: /opt #***

# Organization/lab/individual.
BESMAN_LAB_TYPE: Organization #***

# Name of the owner of the lab. Default is Be-Secure.
BESMAN_LAB_NAME: Be-Secure #***

# This is the local dir where we store the assessment reports. Default is home.
BESMAN_ASSESSMENT_DATASTORE_DIR: $HOME/besecure-ml-assessment-datastore #***

# The remote repo where we store the assessment reports.
BESMAN_ASSESSMENT_DATASTORE_URL: https://github.com/Be-Secure/besecure-ml-assessment-datastore #***

