tools:
  semgrep: "https://github.com/returntocorp/semgrep.git"
  codeql: "https://github.com/github/codeql.git"
  bandit: "https://github.com/PyCQA/bandit.git"
  find_sec_bugs: "https://github.com/find-sec-bugs/find-sec-bugs.git"
  syft: "https://github.com/anchore/syft.git"
  grype: "https://github.com/anchore/grype.git"
  trivy: "https://github.com/aquasecurity/trivy.git"
  cyclonedx_cli: "https://github.com/CycloneDX/cyclonedx-cli.git"
  scancode_toolkit: "https://github.com/nexB/scancode-toolkit.git"
  spdx_tools: "https://github.com/spdx/tools.git"