on:
  push:
    branches:
      - develop
  #pull_request:
  #  branches:
  #    - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Repositry
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Table repo
        uses: actions/checkout@v4
        with:
          repository: Be-Secure/BeSCommunityLabEPPCandidates
          token: ${{ secrets.PAT_TOKEN }}
          path: envs
          
      - name: Check Author
        id: check_author
        run: |
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          CODE_OWNERS=("anilsingla111@gmail.com" "harimohanan@wipro.com")
          if [[ " ${CODE_OWNERS[@]} " =~ " ${AUTHOR_EMAIL} " ]];then
             echo "Code Owner Author Email is ${AUTHOR_EMAIL}"
             echo "IS_CODE_OWNER=true" >> $GITHUB_ENV 
          else
             echo "Non Code Owner Author Email is ${AUTHOR_EMAIL}"
             echo "IS_CODE_OWNER=false" >> $GITHUB_ENV
          fi
      
      - name: Checkout develop branch latest
        run: |
          git fetch origin develop
          git checkout develop
          git pull origin develop
        if: env.IS_CODE_OWNER == 'true'
        
      - name: generate-table
        run: |
          echo "## Available Envs" > temp.md
          echo "" >> temp.md
          echo "| Sr No | Environment Name | Version | File Name |" >> temp.md
          echo "|-------|------------------|---------|-----------|" >> temp.md

          i=0
          for dir in $(find . -maxdepth 2 -type d !  -path '*/\.*' ! -path '*/.git*' ! -path './envs*' | sort ); do
            url1=$(basename "$dir")
            url2=$(basename "$(dirname "$dir")")
            
            if [ "${url1}" != "." ];then
              if [ "${url2}" == "." ];then
                i=$((i+1))
                echo "| $i | \`$url1\` | | |" >> temp.md
              else
                j=1
                for file in $(find "$dir" -maxdepth 1 -type f ! -name '.*' | sort ); do
                  file_name=$(basename "$file")
                  echo "| $i.$j | \`$url2\' | \`$url1\` | \`$file_name\` |" >> temp.md   
                  j=$((j+1))
                done 
              fi
            fi
            
          done
          awk '/## Available Envs/{flag=1;print;getline;while($0!~"^##"&&flag){getline}flag=0}flag{next}1' Environments.md temp.md > Env.new && cp -f Env.new Environments.md
          cd envs
          cp -f ../Environments.md BeSEnvironments.md 

        if: env.IS_CODE_OWNER == 'true'
        
      - name: Commit
        run: |
          cd envs
          if ! git diff --quiet; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git commit -a -m "Updated the env table"
            git push origin HEAD
          fi
        if: env.IS_CODE_OWNER == 'true'
  
