on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Repositry
        uses: actions/checkout@v4

      - name: generate-table
        run: |
          echo "## Available Envs" > temp.md
          echo "" >> temp.md
          echo "| Enviroment Name | Status |" >> temp.md
          echo "|-----------------|--------|" >> temp.md
          for dir in $(find . -maxdepth 1 -type d ! -name '.*' | sort ); do
            folder_name=$(basename "$dir")
            if [ "$folder_name" != "." ];then
              echo "| \`$folder_name\` | Published |" >> temp.md
            fi
          done

          awk '/## Available Envs/{flag=1;print;getline;while($0!~"^##"&&flag){getline}flag=0}flag{next}1' Environments.md temp.md > Env.new && mv Env.new Environments.md
      - name: Commit
        run: |
          if ! git diff --quiet; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add Environments.md
            git commit -a -m "Updated the env table"
            git push
          fi
  
